/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import core.DBmethods;
import java.sql.Timestamp;
import java.util.Calendar;

/**
 *
 * @author Silent1
 */
public class GUI extends javax.swing.JFrame {

    private DBmethods dbmethods;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        dbmethods = new DBmethods();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_vytvorVlak = new javax.swing.JDialog();
        txt_zaciatok = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ciel = new javax.swing.JTextField();
        txt_typ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_datVypr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_datDor = new javax.swing.JTextField();
        btn_createTrain = new javax.swing.JButton();
        btn_endTrainCreation = new javax.swing.JButton();
        dialog_vytvorPohybVoznaVlak = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_typPohybu = new javax.swing.JTextField();
        txt_idSnimaca = new javax.swing.JTextField();
        txt_idVlaku_b = new javax.swing.JTextField();
        btn_vytvorPohyb = new javax.swing.JButton();
        btn_koniec = new javax.swing.JButton();
        dialog_pridajVozen = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_pridanieVozna_idSpolocnosti = new javax.swing.JTextField();
        txt_pridanieVozna_kod = new javax.swing.JTextField();
        txt_pridanieVozna_idVozna = new javax.swing.JTextField();
        txt_pridanieVozna_idSnimaca = new javax.swing.JTextField();
        btn_pridanieVozna_pridaj = new javax.swing.JButton();
        btn_pridanieVozna_koniec = new javax.swing.JButton();
        dialog_vyradVozenZPrevadzky = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_VyradenieVoznaZPrevadzky_Kod = new javax.swing.JTextField();
        txt_VyradenieVoznaZPrevadzky_ID = new javax.swing.JTextField();
        btn_VyradenieVoznaZPrevadzky_Vyrad = new javax.swing.JButton();
        btn_VyradenieVoznaZPrevadzky_Koniec = new javax.swing.JButton();
        dialog_zaradVozenDoVlaku = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_zaradenieVoznaDoVlaku_idVlaku = new javax.swing.JTextField();
        txt_zaradenieVoznaDoVlaku_idVozna = new javax.swing.JTextField();
        txt_zaradenieVoznaDoVlaku_kod = new javax.swing.JTextField();
        txt_zaradenieVoznaDoVlaku_idSnimaca = new javax.swing.JTextField();
        btn_zaradenieVoznaDoVlaku_Zarad = new javax.swing.JButton();
        btn_zaradenieVoznaDoVlaku_Koniec = new javax.swing.JButton();
        dialog_vyradVozenZVlaku = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_vyradenieVoznaZVlaku_idVlaku = new javax.swing.JTextField();
        txt_vyradenieVoznaZVlaku_idVozna = new javax.swing.JTextField();
        txt_vyradenieVoznaZVlaku_kod = new javax.swing.JTextField();
        txt_vyradenieVoznaZVlaku_idSnimaca = new javax.swing.JTextField();
        btn_vyradenieVoznaZVlaku_Vyrad = new javax.swing.JButton();
        btn_vyradenieVoznaZVlaku_Koniec = new javax.swing.JButton();
        dialog_zmenPoholuVozna = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_zmenaPolohyVozna_idVozna = new javax.swing.JTextField();
        txt_zmenaPolohyVozna_kod = new javax.swing.JTextField();
        txt_zmenaPolohyVozna_idSnimaca = new javax.swing.JTextField();
        txt_zmenaPolohyVozna_poznamka = new javax.swing.JTextField();
        btn_zmenaPolohyVozna_Zmen = new javax.swing.JButton();
        btn_zmenaPolohyVozna_koniec = new javax.swing.JButton();
        dialog_vytvorStanicu = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_vytvorenieStanice_nazov = new javax.swing.JTextField();
        txt_vytvorenieStanice_gpsSirka = new javax.swing.JTextField();
        txt_vytvorenieStanice_gpsDlzka = new javax.swing.JTextField();
        btn_vytvorStanicu_vytvor = new javax.swing.JButton();
        btn_vytvorStanicu_koniec = new javax.swing.JButton();
        dialog_zoznamVoznovVStanici = new javax.swing.JDialog();
        jLabel35 = new javax.swing.JLabel();
        radioBtn_zobrazVozneVStanici_vPrevadzke = new javax.swing.JRadioButton();
        jLabel39 = new javax.swing.JLabel();
        txt_zobrazVozneVStanici_idStanice = new javax.swing.JTextField();
        datePicker_ZobrazVozneVStanici_od = new org.jdesktop.swingx.JXDatePicker();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        datePicker_zobrazVozneVStanici_do = new org.jdesktop.swingx.JXDatePicker();
        txt_zobrazVozneVStanici_casOd = new javax.swing.JTextField();
        txt_zobrazVozneVStanici_casDo = new javax.swing.JTextField();
        btn_zobrazVozneVStanici_zobraz = new javax.swing.JToggleButton();
        btn_zobrazVozneVStanici_koniec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        tabbedPane_panel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_createTrain = new javax.swing.JMenuItem();
        menu_vytvorPohybVoznaVlak = new javax.swing.JMenuItem();
        menu_vytvorZelStanicu = new javax.swing.JMenuItem();
        menu_vytvorSnimac = new javax.swing.JMenuItem();
        menu_vytvorPracovnika = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_pridajVozen = new javax.swing.JMenuItem();
        menu_vyradVozen = new javax.swing.JMenuItem();
        menu_zaradVozenDoVlaku = new javax.swing.JMenuItem();
        menu_vyradVozenZVlaku = new javax.swing.JMenuItem();
        menu_zmenPolohuVozna = new javax.swing.JMenuItem();
        menu_vyhladajVozen = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btn_zobrazVlak = new javax.swing.JMenuItem();
        btn_zobrazPohybVoznaVlak = new javax.swing.JMenuItem();
        menu_zobrazPohyb = new javax.swing.JMenuItem();
        menu_zobrazSnimac = new javax.swing.JMenuItem();
        menu_zobrazKolaj = new javax.swing.JMenuItem();
        menu_zobrazStanice = new javax.swing.JMenuItem();
        menu_zobrazVozen = new javax.swing.JMenuItem();
        menu_zobrazSpolocnost = new javax.swing.JMenuItem();
        menu_zobrazTypVozna = new javax.swing.JMenuItem();
        menu_zobrazPouzivatel = new javax.swing.JMenuItem();
        menu_zobrazZaznam = new javax.swing.JMenuItem();
        menu_zobrazPresun = new javax.swing.JMenuItem();
        menu_vystupy = new javax.swing.JMenu();
        menu_zoznamVoznovVStanici = new javax.swing.JMenuItem();

        dialog_vytvorVlak.setMinimumSize(new java.awt.Dimension(400, 392));
        dialog_vytvorVlak.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dialog_vytvorVlak.getContentPane().add(txt_zaciatok, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 90, -1));

        jLabel1.setText("Vytvaranie vlakov");
        dialog_vytvorVlak.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setText("Zaciatok:");
        dialog_vytvorVlak.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel3.setText("Ciel:");
        dialog_vytvorVlak.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 50, 20));
        dialog_vytvorVlak.getContentPane().add(txt_ciel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, -1));
        dialog_vytvorVlak.getContentPane().add(txt_typ, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 90, -1));

        jLabel4.setText("Typ:");
        dialog_vytvorVlak.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel5.setText("Datum vypravenia:");
        dialog_vytvorVlak.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));
        dialog_vytvorVlak.getContentPane().add(txt_datVypr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 90, -1));

        jLabel6.setText("Datum dorazenia:");
        dialog_vytvorVlak.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));
        dialog_vytvorVlak.getContentPane().add(txt_datDor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 90, -1));

        btn_createTrain.setText("Vytvor vlak");
        btn_createTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createTrainActionPerformed(evt);
            }
        });
        dialog_vytvorVlak.getContentPane().add(btn_createTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        btn_endTrainCreation.setText("Koniec");
        btn_endTrainCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_endTrainCreationActionPerformed(evt);
            }
        });
        dialog_vytvorVlak.getContentPane().add(btn_endTrainCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        dialog_vytvorPohybVoznaVlak.setMinimumSize(new java.awt.Dimension(400, 402));
        dialog_vytvorPohybVoznaVlak.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Vytvorenie pohybu vozna");
        dialog_vytvorPohybVoznaVlak.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel8.setText("Typ pohybu:");
        dialog_vytvorPohybVoznaVlak.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 20));

        jLabel9.setText("Id_snimaca:");
        dialog_vytvorPohybVoznaVlak.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel10.setText("Id_vlaku:");
        dialog_vytvorPohybVoznaVlak.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));
        dialog_vytvorPohybVoznaVlak.getContentPane().add(txt_typPohybu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, -1));
        dialog_vytvorPohybVoznaVlak.getContentPane().add(txt_idSnimaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 70, -1));
        dialog_vytvorPohybVoznaVlak.getContentPane().add(txt_idVlaku_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 70, -1));

        btn_vytvorPohyb.setText("Vytvor pohyb");
        btn_vytvorPohyb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vytvorPohybActionPerformed(evt);
            }
        });
        dialog_vytvorPohybVoznaVlak.getContentPane().add(btn_vytvorPohyb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        btn_koniec.setText("Koniec");
        btn_koniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_koniecActionPerformed(evt);
            }
        });
        dialog_vytvorPohybVoznaVlak.getContentPane().add(btn_koniec, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        dialog_pridajVozen.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel11.setText("Pridanie vozna");

        jLabel12.setText("ID spolocnosti:");

        jLabel13.setText("Kod:");

        jLabel14.setText("ID vozna:");

        jLabel15.setText("ID snimaca:");

        btn_pridanieVozna_pridaj.setText("Pridaj vozen");
        btn_pridanieVozna_pridaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pridanieVozna_pridajActionPerformed(evt);
            }
        });

        btn_pridanieVozna_koniec.setText("Koniec");
        btn_pridanieVozna_koniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pridanieVozna_koniecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_pridajVozenLayout = new javax.swing.GroupLayout(dialog_pridajVozen.getContentPane());
        dialog_pridajVozen.getContentPane().setLayout(dialog_pridajVozenLayout);
        dialog_pridajVozenLayout.setHorizontalGroup(
            dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel11))
                    .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(36, 36, 36)
                        .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pridanieVozna_idSnimaca, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(txt_pridanieVozna_idVozna)
                            .addComponent(txt_pridanieVozna_kod)
                            .addComponent(txt_pridanieVozna_idSpolocnosti))))
                .addGap(133, 133, 133))
            .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btn_pridanieVozna_pridaj))
                    .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btn_pridanieVozna_koniec)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialog_pridajVozenLayout.setVerticalGroup(
            dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(45, 45, 45)
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_pridanieVozna_idSpolocnosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_pridanieVozna_kod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_pridanieVozna_idVozna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txt_pridanieVozna_idSnimaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_pridanieVozna_pridaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_pridanieVozna_koniec)
                .addContainerGap())
        );

        jLabel16.setText("Vyradenie vozna z prevadzky");

        jLabel17.setText("Kod:");

        jLabel18.setText("ID vozna:");

        btn_VyradenieVoznaZPrevadzky_Vyrad.setText("Vyrad vozen");
        btn_VyradenieVoznaZPrevadzky_Vyrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VyradenieVoznaZPrevadzky_VyradActionPerformed(evt);
            }
        });

        btn_VyradenieVoznaZPrevadzky_Koniec.setText("Koniec");
        btn_VyradenieVoznaZPrevadzky_Koniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VyradenieVoznaZPrevadzky_KoniecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_vyradVozenZPrevadzkyLayout = new javax.swing.GroupLayout(dialog_vyradVozenZPrevadzky.getContentPane());
        dialog_vyradVozenZPrevadzky.getContentPane().setLayout(dialog_vyradVozenZPrevadzkyLayout);
        dialog_vyradVozenZPrevadzkyLayout.setHorizontalGroup(
            dialog_vyradVozenZPrevadzkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_vyradVozenZPrevadzkyLayout.createSequentialGroup()
                .addGroup(dialog_vyradVozenZPrevadzkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_vyradVozenZPrevadzkyLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel16))
                    .addGroup(dialog_vyradVozenZPrevadzkyLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(dialog_vyradVozenZPrevadzkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(23, 23, 23)
                        .addGroup(dialog_vyradVozenZPrevadzkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_VyradenieVoznaZPrevadzky_Kod, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(txt_VyradenieVoznaZPrevadzky_ID)))
                    .addGroup(dialog_vyradVozenZPrevadzkyLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btn_VyradenieVoznaZPrevadzky_Vyrad)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_vyradVozenZPrevadzkyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_VyradenieVoznaZPrevadzky_Koniec)
                .addGap(179, 179, 179))
        );
        dialog_vyradVozenZPrevadzkyLayout.setVerticalGroup(
            dialog_vyradVozenZPrevadzkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_vyradVozenZPrevadzkyLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel16)
                .addGap(31, 31, 31)
                .addGroup(dialog_vyradVozenZPrevadzkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_VyradenieVoznaZPrevadzky_Kod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_vyradVozenZPrevadzkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_VyradenieVoznaZPrevadzky_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btn_VyradenieVoznaZPrevadzky_Vyrad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btn_VyradenieVoznaZPrevadzky_Koniec)
                .addGap(16, 16, 16))
        );

        jLabel19.setText("Zaradenie vozna do vlaku");

        jLabel20.setText("ID vlaku:");

        jLabel21.setText("ID vozna:");

        jLabel22.setText("Kod:");

        jLabel23.setText("ID snimaca:");

        btn_zaradenieVoznaDoVlaku_Zarad.setText("Zarad vozen");
        btn_zaradenieVoznaDoVlaku_Zarad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zaradenieVoznaDoVlaku_ZaradActionPerformed(evt);
            }
        });

        btn_zaradenieVoznaDoVlaku_Koniec.setText("Koniec");

        javax.swing.GroupLayout dialog_zaradVozenDoVlakuLayout = new javax.swing.GroupLayout(dialog_zaradVozenDoVlaku.getContentPane());
        dialog_zaradVozenDoVlaku.getContentPane().setLayout(dialog_zaradVozenDoVlakuLayout);
        dialog_zaradVozenDoVlakuLayout.setHorizontalGroup(
            dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_zaradVozenDoVlakuLayout.createSequentialGroup()
                .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_zaradVozenDoVlakuLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel19))
                    .addGroup(dialog_zaradVozenDoVlakuLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(dialog_zaradVozenDoVlakuLayout.createSequentialGroup()
                                .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialog_zaradVozenDoVlakuLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(dialog_zaradVozenDoVlakuLayout.createSequentialGroup()
                                        .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addGap(63, 63, 63)))
                                .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_zaradenieVoznaDoVlaku_idVlaku, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(txt_zaradenieVoznaDoVlaku_idVozna)
                                    .addComponent(txt_zaradenieVoznaDoVlaku_kod)
                                    .addComponent(txt_zaradenieVoznaDoVlaku_idSnimaca))))))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_zaradVozenDoVlakuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_zaradenieVoznaDoVlaku_Zarad)
                    .addGroup(dialog_zaradVozenDoVlakuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_zaradenieVoznaDoVlaku_Koniec)))
                .addGap(233, 233, 233))
        );
        dialog_zaradVozenDoVlakuLayout.setVerticalGroup(
            dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_zaradVozenDoVlakuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addGap(27, 27, 27)
                .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_zaradenieVoznaDoVlaku_idVlaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_zaradenieVoznaDoVlaku_idVozna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_zaradenieVoznaDoVlaku_kod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_zaradVozenDoVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txt_zaradenieVoznaDoVlaku_idSnimaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_zaradenieVoznaDoVlaku_Zarad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btn_zaradenieVoznaDoVlaku_Koniec)
                .addGap(16, 16, 16))
        );

        jLabel24.setText("Vyradenie vozna z vlaku");

        jLabel25.setText("ID vlaku:");

        jLabel26.setText("ID vozna:");

        jLabel27.setText("Kod:");

        jLabel28.setText("ID snimaca:");

        btn_vyradenieVoznaZVlaku_Vyrad.setText("Vyrad vozen z vlaku");
        btn_vyradenieVoznaZVlaku_Vyrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vyradenieVoznaZVlaku_VyradActionPerformed(evt);
            }
        });

        btn_vyradenieVoznaZVlaku_Koniec.setText("Koniec");
        btn_vyradenieVoznaZVlaku_Koniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vyradenieVoznaZVlaku_KoniecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_vyradVozenZVlakuLayout = new javax.swing.GroupLayout(dialog_vyradVozenZVlaku.getContentPane());
        dialog_vyradVozenZVlaku.getContentPane().setLayout(dialog_vyradVozenZVlakuLayout);
        dialog_vyradVozenZVlakuLayout.setHorizontalGroup(
            dialog_vyradVozenZVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_vyradVozenZVlakuLayout.createSequentialGroup()
                .addGroup(dialog_vyradVozenZVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_vyradVozenZVlakuLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel24))
                    .addGroup(dialog_vyradVozenZVlakuLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(dialog_vyradVozenZVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(34, 34, 34)
                        .addGroup(dialog_vyradVozenZVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_vyradenieVoznaZVlaku_idVlaku)
                            .addComponent(txt_vyradenieVoznaZVlaku_idVozna)
                            .addComponent(txt_vyradenieVoznaZVlaku_kod)
                            .addComponent(txt_vyradenieVoznaZVlaku_idSnimaca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialog_vyradVozenZVlakuLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btn_vyradenieVoznaZVlaku_Vyrad))
                    .addGroup(dialog_vyradVozenZVlakuLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btn_vyradenieVoznaZVlaku_Koniec)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        dialog_vyradVozenZVlakuLayout.setVerticalGroup(
            dialog_vyradVozenZVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_vyradVozenZVlakuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel24)
                .addGap(31, 31, 31)
                .addGroup(dialog_vyradVozenZVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txt_vyradenieVoznaZVlaku_idVlaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_vyradVozenZVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_vyradenieVoznaZVlaku_idVozna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_vyradVozenZVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_vyradenieVoznaZVlaku_kod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_vyradVozenZVlakuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_vyradenieVoznaZVlaku_idSnimaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_vyradenieVoznaZVlaku_Vyrad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btn_vyradenieVoznaZVlaku_Koniec)
                .addContainerGap())
        );

        jLabel29.setText("Zmena polohy vozna v stanici");

        jLabel30.setText("ID vozna:");

        jLabel31.setText("Kod:");

        jLabel32.setText("ID snimaca:");

        jLabel33.setText("Poznamka:");

        btn_zmenaPolohyVozna_Zmen.setText("Zmen polohu vozna");
        btn_zmenaPolohyVozna_Zmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zmenaPolohyVozna_ZmenActionPerformed(evt);
            }
        });

        btn_zmenaPolohyVozna_koniec.setText("Koniec");
        btn_zmenaPolohyVozna_koniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zmenaPolohyVozna_koniecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_zmenPoholuVoznaLayout = new javax.swing.GroupLayout(dialog_zmenPoholuVozna.getContentPane());
        dialog_zmenPoholuVozna.getContentPane().setLayout(dialog_zmenPoholuVoznaLayout);
        dialog_zmenPoholuVoznaLayout.setHorizontalGroup(
            dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_zmenPoholuVoznaLayout.createSequentialGroup()
                .addGroup(dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_zmenPoholuVoznaLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel29))
                    .addGroup(dialog_zmenPoholuVoznaLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33)
                            .addComponent(jLabel30))
                        .addGap(68, 68, 68)
                        .addGroup(dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_zmenaPolohyVozna_poznamka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialog_zmenPoholuVoznaLayout.createSequentialGroup()
                                .addGroup(dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_zmenaPolohyVozna_idVozna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(txt_zmenaPolohyVozna_kod, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_zmenaPolohyVozna_idSnimaca, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
            .addGroup(dialog_zmenPoholuVoznaLayout.createSequentialGroup()
                .addGroup(dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_zmenPoholuVoznaLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btn_zmenaPolohyVozna_Zmen))
                    .addGroup(dialog_zmenPoholuVoznaLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btn_zmenaPolohyVozna_koniec)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialog_zmenPoholuVoznaLayout.setVerticalGroup(
            dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_zmenPoholuVoznaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel29)
                .addGap(27, 27, 27)
                .addGroup(dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_zmenaPolohyVozna_idVozna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txt_zmenaPolohyVozna_kod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt_zmenaPolohyVozna_idSnimaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_zmenPoholuVoznaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(txt_zmenaPolohyVozna_poznamka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_zmenaPolohyVozna_Zmen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btn_zmenaPolohyVozna_koniec)
                .addGap(14, 14, 14))
        );

        jLabel34.setText("Vytvorenie stanice");

        jLabel36.setText("Nazov:");

        jLabel37.setText("GPS sirka:");

        jLabel38.setText("GPS dlzka:");

        btn_vytvorStanicu_vytvor.setText("Vytvor stanicu");
        btn_vytvorStanicu_vytvor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vytvorStanicu_vytvorActionPerformed(evt);
            }
        });

        btn_vytvorStanicu_koniec.setText("Koniec");
        btn_vytvorStanicu_koniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vytvorStanicu_koniecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_vytvorStanicuLayout = new javax.swing.GroupLayout(dialog_vytvorStanicu.getContentPane());
        dialog_vytvorStanicu.getContentPane().setLayout(dialog_vytvorStanicuLayout);
        dialog_vytvorStanicuLayout.setHorizontalGroup(
            dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_vytvorStanicuLayout.createSequentialGroup()
                .addGroup(dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_vytvorStanicuLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_vytvorenieStanice_nazov, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialog_vytvorStanicuLayout.createSequentialGroup()
                                .addGroup(dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38))
                                .addGap(41, 41, 41)
                                .addGroup(dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_vytvorenieStanice_gpsSirka, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(txt_vytvorenieStanice_gpsDlzka)))))
                    .addGroup(dialog_vytvorStanicuLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_vytvorStanicu_vytvor)
                            .addComponent(jLabel34)))
                    .addGroup(dialog_vytvorStanicuLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btn_vytvorStanicu_koniec)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        dialog_vytvorStanicuLayout.setVerticalGroup(
            dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_vytvorStanicuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addGroup(dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txt_vytvorenieStanice_nazov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txt_vytvorenieStanice_gpsSirka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_vytvorStanicuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txt_vytvorenieStanice_gpsDlzka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_vytvorStanicu_vytvor)
                .addGap(37, 37, 37)
                .addComponent(btn_vytvorStanicu_koniec)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel35.setText("Zobraz vozne v stanici");

        radioBtn_zobrazVozneVStanici_vPrevadzke.setSelected(true);
        radioBtn_zobrazVozneVStanici_vPrevadzke.setText("V prevadzke");
        radioBtn_zobrazVozneVStanici_vPrevadzke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn_zobrazVozneVStanici_vPrevadzkeActionPerformed(evt);
            }
        });

        jLabel39.setText("ID stanice:");

        jLabel40.setText("Datum a cas od:");

        jLabel41.setText("Datum a cas do:");

        txt_zobrazVozneVStanici_casOd.setText("07:00");

        txt_zobrazVozneVStanici_casDo.setText("22:00");

        btn_zobrazVozneVStanici_zobraz.setText("Zobraz vozne");
        btn_zobrazVozneVStanici_zobraz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zobrazVozneVStanici_zobrazActionPerformed(evt);
            }
        });

        btn_zobrazVozneVStanici_koniec.setText("Koniec");
        btn_zobrazVozneVStanici_koniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zobrazVozneVStanici_koniecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_zoznamVoznovVStaniciLayout = new javax.swing.GroupLayout(dialog_zoznamVoznovVStanici.getContentPane());
        dialog_zoznamVoznovVStanici.getContentPane().setLayout(dialog_zoznamVoznovVStaniciLayout);
        dialog_zoznamVoznovVStaniciLayout.setHorizontalGroup(
            dialog_zoznamVoznovVStaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_zoznamVoznovVStaniciLayout.createSequentialGroup()
                .addGroup(dialog_zoznamVoznovVStaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_zoznamVoznovVStaniciLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(dialog_zoznamVoznovVStaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBtn_zobrazVozneVStanici_vPrevadzke)
                            .addGroup(dialog_zoznamVoznovVStaniciLayout.createSequentialGroup()
                                .addGroup(dialog_zoznamVoznovVStaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41))
                                .addGap(32, 32, 32)
                                .addGroup(dialog_zoznamVoznovVStaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_zobrazVozneVStanici_idStanice, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dialog_zoznamVoznovVStaniciLayout.createSequentialGroup()
                                        .addComponent(datePicker_zobrazVozneVStanici_do, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_zobrazVozneVStanici_casDo))
                                    .addGroup(dialog_zoznamVoznovVStaniciLayout.createSequentialGroup()
                                        .addComponent(datePicker_ZobrazVozneVStanici_od, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_zobrazVozneVStanici_casOd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(dialog_zoznamVoznovVStaniciLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(btn_zobrazVozneVStanici_zobraz))
                    .addGroup(dialog_zoznamVoznovVStaniciLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel35))
                    .addGroup(dialog_zoznamVoznovVStaniciLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btn_zobrazVozneVStanici_koniec)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        dialog_zoznamVoznovVStaniciLayout.setVerticalGroup(
            dialog_zoznamVoznovVStaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_zoznamVoznovVStaniciLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel35)
                .addGap(29, 29, 29)
                .addComponent(radioBtn_zobrazVozneVStanici_vPrevadzke)
                .addGap(18, 18, 18)
                .addGroup(dialog_zoznamVoznovVStaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txt_zobrazVozneVStanici_idStanice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_zoznamVoznovVStaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePicker_ZobrazVozneVStanici_od, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(txt_zobrazVozneVStanici_casOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_zoznamVoznovVStaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePicker_zobrazVozneVStanici_do, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(txt_zobrazVozneVStanici_casDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_zobrazVozneVStanici_zobraz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btn_zobrazVozneVStanici_koniec)
                .addGap(18, 18, 18))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jButton1.setText("Vytvor stanicu");

        jButton2.setText("Zobraz vsetky stanice");

        jButton3.setText("Najdi stanicu");

        jButton4.setText("Zrus stanicu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        tabbedPane_panel.addTab("Stanica", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Kolaj", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Snimac", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Vozen", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Vlak", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Pohyb", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Presun", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Pohyb vozna vlak", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Spolocnost", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Typ vozna", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Pouzivatel", jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        tabbedPane_panel.addTab("Zaznam", jPanel12);

        jMenu1.setText("File");

        menu_Exit.setText("Exit");
        menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vytvor");

        menu_createTrain.setText("Vytvor vlak");
        menu_createTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_createTrainActionPerformed(evt);
            }
        });
        jMenu2.add(menu_createTrain);

        menu_vytvorPohybVoznaVlak.setText("Vytvor pohyb vozna - vlak");
        menu_vytvorPohybVoznaVlak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vytvorPohybVoznaVlakActionPerformed(evt);
            }
        });
        jMenu2.add(menu_vytvorPohybVoznaVlak);

        menu_vytvorZelStanicu.setText("Vytvor zel. stanicu");
        menu_vytvorZelStanicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vytvorZelStanicuActionPerformed(evt);
            }
        });
        jMenu2.add(menu_vytvorZelStanicu);

        menu_vytvorSnimac.setText("Vytvor snimac");
        jMenu2.add(menu_vytvorSnimac);

        menu_vytvorPracovnika.setText("Vytvor pracovnika");
        jMenu2.add(menu_vytvorPracovnika);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("PL/SQL ulohy");

        menu_pridajVozen.setText("Pridaj vozen");
        menu_pridajVozen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pridajVozenActionPerformed(evt);
            }
        });
        jMenu4.add(menu_pridajVozen);

        menu_vyradVozen.setText("Vyrad vozen");
        menu_vyradVozen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vyradVozenActionPerformed(evt);
            }
        });
        jMenu4.add(menu_vyradVozen);

        menu_zaradVozenDoVlaku.setText("Zarad vozen do vlaku");
        menu_zaradVozenDoVlaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zaradVozenDoVlakuActionPerformed(evt);
            }
        });
        jMenu4.add(menu_zaradVozenDoVlaku);

        menu_vyradVozenZVlaku.setText("Vyrad vozen z vlaku");
        menu_vyradVozenZVlaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vyradVozenZVlakuActionPerformed(evt);
            }
        });
        jMenu4.add(menu_vyradVozenZVlaku);

        menu_zmenPolohuVozna.setText("Zmen polohu vozna v stanici");
        menu_zmenPolohuVozna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zmenPolohuVoznaActionPerformed(evt);
            }
        });
        jMenu4.add(menu_zmenPolohuVozna);

        menu_vyhladajVozen.setText("Vyhladaj najblizsi volny vozen");
        menu_vyhladajVozen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vyhladajVozenActionPerformed(evt);
            }
        });
        jMenu4.add(menu_vyhladajVozen);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Debug-zobrazenie tabuliek");

        btn_zobrazVlak.setText("Vlak");
        btn_zobrazVlak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zobrazVlakActionPerformed(evt);
            }
        });
        jMenu3.add(btn_zobrazVlak);

        btn_zobrazPohybVoznaVlak.setText("Pohyb vozna vlak");
        btn_zobrazPohybVoznaVlak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zobrazPohybVoznaVlakActionPerformed(evt);
            }
        });
        jMenu3.add(btn_zobrazPohybVoznaVlak);

        menu_zobrazPohyb.setText("Pohyb");
        menu_zobrazPohyb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazPohybActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazPohyb);

        menu_zobrazSnimac.setText("Snimac");
        menu_zobrazSnimac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazSnimacActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazSnimac);

        menu_zobrazKolaj.setText("Kolaj");
        menu_zobrazKolaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazKolajActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazKolaj);

        menu_zobrazStanice.setText("Stanica");
        menu_zobrazStanice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazStaniceActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazStanice);

        menu_zobrazVozen.setText("Vozen");
        menu_zobrazVozen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazVozenActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazVozen);

        menu_zobrazSpolocnost.setText("Spolocnost");
        menu_zobrazSpolocnost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazSpolocnostActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazSpolocnost);

        menu_zobrazTypVozna.setText("Typ vozna");
        menu_zobrazTypVozna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazTypVoznaActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazTypVozna);

        menu_zobrazPouzivatel.setText("Pouzivatel");
        menu_zobrazPouzivatel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazPouzivatelActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazPouzivatel);

        menu_zobrazZaznam.setText("Zaznam");
        menu_zobrazZaznam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazZaznamActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazZaznam);

        menu_zobrazPresun.setText("Presun");
        menu_zobrazPresun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zobrazPresunActionPerformed(evt);
            }
        });
        jMenu3.add(menu_zobrazPresun);

        jMenuBar1.add(jMenu3);

        menu_vystupy.setText("Vystupy");

        menu_zoznamVoznovVStanici.setText("Zoznam voznov v stanici");
        menu_zoznamVoznovVStanici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zoznamVoznovVStaniciActionPerformed(evt);
            }
        });
        menu_vystupy.add(menu_zoznamVoznovVStanici);

        jMenuBar1.add(menu_vystupy);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabbedPane_panel)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_ExitActionPerformed

    private void btn_createTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createTrainActionPerformed
        
        int    zaciatok  = Integer.parseInt(txt_zaciatok.getText());
        int    ciel      = Integer.parseInt(txt_ciel.getText());
        int    typ       = Integer.parseInt(txt_typ.getText());
        String datVyp    = txt_datVypr.getText();
        String datDor    = txt_datDor.getText();
        
        dbmethods.vytvorVlak(zaciatok, ciel, typ, datVyp, datDor);
        
    }//GEN-LAST:event_btn_createTrainActionPerformed

    private void menu_createTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_createTrainActionPerformed
        dialog_vytvorVlak.pack();
        dialog_vytvorVlak.setVisible(true);
    }//GEN-LAST:event_menu_createTrainActionPerformed

    private void btn_endTrainCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_endTrainCreationActionPerformed
        dialog_vytvorVlak.setVisible(false);
    }//GEN-LAST:event_btn_endTrainCreationActionPerformed

    private void btn_vytvorPohybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vytvorPohybActionPerformed
        
        char   typPohybu = txt_typPohybu.getText().charAt(0);
        int    idSnimaca = Integer.parseInt(txt_idSnimaca.getText());
        int    idVlaku   = Integer.parseInt(txt_idVlaku_b.getText());
        
        dbmethods.vytvorPohybVoznaVlak(typPohybu, idSnimaca, idVlaku);
        
    }//GEN-LAST:event_btn_vytvorPohybActionPerformed

    private void btn_koniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_koniecActionPerformed
        dialog_vytvorPohybVoznaVlak.setVisible(false);
    }//GEN-LAST:event_btn_koniecActionPerformed

    private void menu_vytvorPohybVoznaVlakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vytvorPohybVoznaVlakActionPerformed
        dialog_vytvorPohybVoznaVlak.pack();
        dialog_vytvorPohybVoznaVlak.setVisible(true);
    }//GEN-LAST:event_menu_vytvorPohybVoznaVlakActionPerformed

    private void btn_zobrazVlakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zobrazVlakActionPerformed
        txtArea.setText(dbmethods.zobrazVlak());
    }//GEN-LAST:event_btn_zobrazVlakActionPerformed

    private void btn_zobrazPohybVoznaVlakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zobrazPohybVoznaVlakActionPerformed
        txtArea.setText(dbmethods.zobrazPohybVoznaVlak());
    }//GEN-LAST:event_btn_zobrazPohybVoznaVlakActionPerformed

    private void menu_pridajVozenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pridajVozenActionPerformed
        dialog_pridajVozen.pack();
        dialog_pridajVozen.setVisible(true);
    }//GEN-LAST:event_menu_pridajVozenActionPerformed

    private void menu_vyradVozenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vyradVozenActionPerformed
        dialog_vyradVozenZPrevadzky.pack();
        dialog_vyradVozenZPrevadzky.setVisible(true);
    }//GEN-LAST:event_menu_vyradVozenActionPerformed

    private void menu_zaradVozenDoVlakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zaradVozenDoVlakuActionPerformed
        dialog_zaradVozenDoVlaku.pack();
        dialog_zaradVozenDoVlaku.setVisible(true);
    }//GEN-LAST:event_menu_zaradVozenDoVlakuActionPerformed

    private void menu_vyradVozenZVlakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vyradVozenZVlakuActionPerformed
        dialog_vyradVozenZVlaku.pack();
        dialog_vyradVozenZVlaku.setVisible(true);
    }//GEN-LAST:event_menu_vyradVozenZVlakuActionPerformed

    private void menu_zmenPolohuVoznaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zmenPolohuVoznaActionPerformed
        dialog_zmenPoholuVozna.pack();
        dialog_zmenPoholuVozna.setVisible(true);
    }//GEN-LAST:event_menu_zmenPolohuVoznaActionPerformed

    private void menu_vyhladajVozenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vyhladajVozenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_vyhladajVozenActionPerformed

    private void btn_pridanieVozna_pridajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pridanieVozna_pridajActionPerformed
        int idSpolocnosti = Integer.parseInt(txt_pridanieVozna_idSpolocnosti.getText());
        int kod           = Integer.parseInt(txt_pridanieVozna_kod.getText());
        int idVozna       = Integer.parseInt(txt_pridanieVozna_idVozna.getText());
        int idSnimaca     = Integer.parseInt(txt_pridanieVozna_idSnimaca.getText());
        
        dbmethods.pridajVozen(idSpolocnosti, kod, idVozna, idSnimaca);
    }//GEN-LAST:event_btn_pridanieVozna_pridajActionPerformed

    private void btn_pridanieVozna_koniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pridanieVozna_koniecActionPerformed
        dialog_pridajVozen.setVisible(false);
    }//GEN-LAST:event_btn_pridanieVozna_koniecActionPerformed

    private void btn_VyradenieVoznaZPrevadzky_VyradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VyradenieVoznaZPrevadzky_VyradActionPerformed
        int kod     = Integer.parseInt(txt_VyradenieVoznaZPrevadzky_Kod.getText());
        int idVozna = Integer.parseInt(txt_VyradenieVoznaZPrevadzky_ID.getText());
        
        dbmethods.vyradVozen(kod, idVozna);
    }//GEN-LAST:event_btn_VyradenieVoznaZPrevadzky_VyradActionPerformed

    private void btn_VyradenieVoznaZPrevadzky_KoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VyradenieVoznaZPrevadzky_KoniecActionPerformed
        dialog_vyradVozenZPrevadzky.setVisible(false);
    }//GEN-LAST:event_btn_VyradenieVoznaZPrevadzky_KoniecActionPerformed

    private void btn_zaradenieVoznaDoVlaku_ZaradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zaradenieVoznaDoVlaku_ZaradActionPerformed
        int idVlaku   = Integer.parseInt(txt_zaradenieVoznaDoVlaku_idVlaku.getText());
        int idVozna   = Integer.parseInt(txt_zaradenieVoznaDoVlaku_idVozna.getText());
        int kod       = Integer.parseInt(txt_zaradenieVoznaDoVlaku_kod.getText());
        int idSnimaca = Integer.parseInt(txt_zaradenieVoznaDoVlaku_idSnimaca.getText());
        
        dbmethods.zaradVozenDoVlaku(idVlaku, idVozna, kod, idSnimaca);
    }//GEN-LAST:event_btn_zaradenieVoznaDoVlaku_ZaradActionPerformed

    private void btn_vyradenieVoznaZVlaku_VyradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vyradenieVoznaZVlaku_VyradActionPerformed
        int idVlaku   = Integer.parseInt(txt_vyradenieVoznaZVlaku_idVlaku.getText());
        int idVozna   = Integer.parseInt(txt_vyradenieVoznaZVlaku_idVozna.getText());
        int kod       = Integer.parseInt(txt_vyradenieVoznaZVlaku_kod.getText());
        int idSnimaca = Integer.parseInt(txt_vyradenieVoznaZVlaku_idSnimaca.getText());
        
        dbmethods.vyradVozenZVlaku(idVlaku, idVozna, kod, idSnimaca);
    }//GEN-LAST:event_btn_vyradenieVoznaZVlaku_VyradActionPerformed

    private void btn_vyradenieVoznaZVlaku_KoniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vyradenieVoznaZVlaku_KoniecActionPerformed
        dialog_vyradVozenZVlaku.setVisible(false);
    }//GEN-LAST:event_btn_vyradenieVoznaZVlaku_KoniecActionPerformed

    private void btn_zmenaPolohyVozna_ZmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zmenaPolohyVozna_ZmenActionPerformed
        int idVozna     = Integer.parseInt(txt_zmenaPolohyVozna_idVozna.getText());
        int kod         = Integer.parseInt(txt_zmenaPolohyVozna_kod.getText());
        int idSnimaca   = Integer.parseInt(txt_zmenaPolohyVozna_idSnimaca.getText());
        String poznamka = txt_zmenaPolohyVozna_poznamka.getText();
        
        dbmethods.zmenPoholuVoznaVStanici(idVozna, kod, idSnimaca, poznamka);
    }//GEN-LAST:event_btn_zmenaPolohyVozna_ZmenActionPerformed

    private void btn_zmenaPolohyVozna_koniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zmenaPolohyVozna_koniecActionPerformed
        dialog_zmenPoholuVozna.setVisible(false);
    }//GEN-LAST:event_btn_zmenaPolohyVozna_koniecActionPerformed

    private void menu_zobrazPohybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazPohybActionPerformed
        txtArea.setText(dbmethods.zobrazPohyb());
    }//GEN-LAST:event_menu_zobrazPohybActionPerformed

    private void menu_zobrazSnimacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazSnimacActionPerformed
        txtArea.setText(dbmethods.zobrazSnimac());
    }//GEN-LAST:event_menu_zobrazSnimacActionPerformed

    private void menu_zobrazKolajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazKolajActionPerformed
        txtArea.setText(dbmethods.zobrazKolaj());
    }//GEN-LAST:event_menu_zobrazKolajActionPerformed

    private void menu_zobrazStaniceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazStaniceActionPerformed
        txtArea.setText(dbmethods.zobrazStanice());
    }//GEN-LAST:event_menu_zobrazStaniceActionPerformed

    private void menu_zobrazVozenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazVozenActionPerformed
        txtArea.setText(dbmethods.zobrazVozen());
    }//GEN-LAST:event_menu_zobrazVozenActionPerformed

    private void menu_zobrazSpolocnostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazSpolocnostActionPerformed
        txtArea.setText(dbmethods.zobrazSpolocnost());
    }//GEN-LAST:event_menu_zobrazSpolocnostActionPerformed

    private void menu_zobrazTypVoznaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazTypVoznaActionPerformed
        txtArea.setText(dbmethods.zobrazTypVozna());
    }//GEN-LAST:event_menu_zobrazTypVoznaActionPerformed

    private void menu_zobrazPouzivatelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazPouzivatelActionPerformed
        txtArea.setText(dbmethods.zobrazPouzivatel());
    }//GEN-LAST:event_menu_zobrazPouzivatelActionPerformed

    private void menu_zobrazZaznamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazZaznamActionPerformed
        txtArea.setText(dbmethods.zobrazZaznam());
    }//GEN-LAST:event_menu_zobrazZaznamActionPerformed

    private void menu_zobrazPresunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zobrazPresunActionPerformed
        txtArea.setText(dbmethods.zobrazPresun());
    }//GEN-LAST:event_menu_zobrazPresunActionPerformed

    private void btn_vytvorStanicu_vytvorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vytvorStanicu_vytvorActionPerformed
        
        String nazov = txt_vytvorenieStanice_nazov.getText();
        float  gpsSirka = Float.parseFloat(txt_vytvorenieStanice_gpsSirka.getText());
        float  gpsDlzka = Float.parseFloat(txt_vytvorenieStanice_gpsDlzka.getText());
        
        dbmethods.vytvorStanicu(nazov, gpsSirka, gpsDlzka);
    }//GEN-LAST:event_btn_vytvorStanicu_vytvorActionPerformed

    private void btn_vytvorStanicu_koniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vytvorStanicu_koniecActionPerformed
        dialog_vytvorStanicu.setVisible(false);
    }//GEN-LAST:event_btn_vytvorStanicu_koniecActionPerformed

    private void menu_vytvorZelStanicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vytvorZelStanicuActionPerformed
        dialog_vytvorStanicu.pack();
        dialog_vytvorStanicu.setVisible(true);         
    }//GEN-LAST:event_menu_vytvorZelStanicuActionPerformed

    private void menu_zoznamVoznovVStaniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zoznamVoznovVStaniciActionPerformed
        dialog_zoznamVoznovVStanici.pack();
        dialog_zoznamVoznovVStanici.setVisible(true);
    }//GEN-LAST:event_menu_zoznamVoznovVStaniciActionPerformed

    private void radioBtn_zobrazVozneVStanici_vPrevadzkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn_zobrazVozneVStanici_vPrevadzkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtn_zobrazVozneVStanici_vPrevadzkeActionPerformed

    private void btn_zobrazVozneVStanici_zobrazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zobrazVozneVStanici_zobrazActionPerformed
        Calendar cal = Calendar.getInstance();
        
        boolean vPrevadzke = radioBtn_zobrazVozneVStanici_vPrevadzke.isSelected();
        int     idStanice  = Integer.parseInt(txt_zobrazVozneVStanici_idStanice.getText());
        
        datePicker_ZobrazVozneVStanici_od.getDate().setHours(Integer.parseInt(txt_zobrazVozneVStanici_casOd.getText().substring(0, 2)));
        datePicker_ZobrazVozneVStanici_od.getDate().setMinutes(Integer.parseInt(txt_zobrazVozneVStanici_casOd.getText().substring(3, 5)));
        
        datePicker_zobrazVozneVStanici_do.getDate().setHours(Integer.parseInt(txt_zobrazVozneVStanici_casDo.getText().substring(0, 2)));
        datePicker_zobrazVozneVStanici_do.getDate().setMinutes(Integer.parseInt(txt_zobrazVozneVStanici_casDo.getText().substring(3, 5)));
        
        Timestamp ts_od = new Timestamp(datePicker_ZobrazVozneVStanici_od.getDate().getTime());
        Timestamp ts_do = new Timestamp(datePicker_zobrazVozneVStanici_do.getDate().getTime());
        
        txtArea.setText(dbmethods.zoznamVoznovVStanici(vPrevadzke, idStanice, ts_od, ts_do));
    }//GEN-LAST:event_btn_zobrazVozneVStanici_zobrazActionPerformed

    private void btn_zobrazVozneVStanici_koniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zobrazVozneVStanici_koniecActionPerformed
        dialog_zoznamVoznovVStanici.setVisible(false);
    }//GEN-LAST:event_btn_zobrazVozneVStanici_koniecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_VyradenieVoznaZPrevadzky_Koniec;
    private javax.swing.JButton btn_VyradenieVoznaZPrevadzky_Vyrad;
    private javax.swing.JButton btn_createTrain;
    private javax.swing.JButton btn_endTrainCreation;
    private javax.swing.JButton btn_koniec;
    private javax.swing.JButton btn_pridanieVozna_koniec;
    private javax.swing.JButton btn_pridanieVozna_pridaj;
    private javax.swing.JButton btn_vyradenieVoznaZVlaku_Koniec;
    private javax.swing.JButton btn_vyradenieVoznaZVlaku_Vyrad;
    private javax.swing.JButton btn_vytvorPohyb;
    private javax.swing.JButton btn_vytvorStanicu_koniec;
    private javax.swing.JButton btn_vytvorStanicu_vytvor;
    private javax.swing.JButton btn_zaradenieVoznaDoVlaku_Koniec;
    private javax.swing.JButton btn_zaradenieVoznaDoVlaku_Zarad;
    private javax.swing.JButton btn_zmenaPolohyVozna_Zmen;
    private javax.swing.JButton btn_zmenaPolohyVozna_koniec;
    private javax.swing.JMenuItem btn_zobrazPohybVoznaVlak;
    private javax.swing.JMenuItem btn_zobrazVlak;
    private javax.swing.JButton btn_zobrazVozneVStanici_koniec;
    private javax.swing.JToggleButton btn_zobrazVozneVStanici_zobraz;
    private org.jdesktop.swingx.JXDatePicker datePicker_ZobrazVozneVStanici_od;
    private org.jdesktop.swingx.JXDatePicker datePicker_zobrazVozneVStanici_do;
    private javax.swing.JDialog dialog_pridajVozen;
    private javax.swing.JDialog dialog_vyradVozenZPrevadzky;
    private javax.swing.JDialog dialog_vyradVozenZVlaku;
    private javax.swing.JDialog dialog_vytvorPohybVoznaVlak;
    private javax.swing.JDialog dialog_vytvorStanicu;
    private javax.swing.JDialog dialog_vytvorVlak;
    private javax.swing.JDialog dialog_zaradVozenDoVlaku;
    private javax.swing.JDialog dialog_zmenPoholuVozna;
    private javax.swing.JDialog dialog_zoznamVoznovVStanici;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu_Exit;
    private javax.swing.JMenuItem menu_createTrain;
    private javax.swing.JMenuItem menu_pridajVozen;
    private javax.swing.JMenuItem menu_vyhladajVozen;
    private javax.swing.JMenuItem menu_vyradVozen;
    private javax.swing.JMenuItem menu_vyradVozenZVlaku;
    private javax.swing.JMenu menu_vystupy;
    private javax.swing.JMenuItem menu_vytvorPohybVoznaVlak;
    private javax.swing.JMenuItem menu_vytvorPracovnika;
    private javax.swing.JMenuItem menu_vytvorSnimac;
    private javax.swing.JMenuItem menu_vytvorZelStanicu;
    private javax.swing.JMenuItem menu_zaradVozenDoVlaku;
    private javax.swing.JMenuItem menu_zmenPolohuVozna;
    private javax.swing.JMenuItem menu_zobrazKolaj;
    private javax.swing.JMenuItem menu_zobrazPohyb;
    private javax.swing.JMenuItem menu_zobrazPouzivatel;
    private javax.swing.JMenuItem menu_zobrazPresun;
    private javax.swing.JMenuItem menu_zobrazSnimac;
    private javax.swing.JMenuItem menu_zobrazSpolocnost;
    private javax.swing.JMenuItem menu_zobrazStanice;
    private javax.swing.JMenuItem menu_zobrazTypVozna;
    private javax.swing.JMenuItem menu_zobrazVozen;
    private javax.swing.JMenuItem menu_zobrazZaznam;
    private javax.swing.JMenuItem menu_zoznamVoznovVStanici;
    private javax.swing.JRadioButton radioBtn_zobrazVozneVStanici_vPrevadzke;
    private javax.swing.JTabbedPane tabbedPane_panel;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txt_VyradenieVoznaZPrevadzky_ID;
    private javax.swing.JTextField txt_VyradenieVoznaZPrevadzky_Kod;
    private javax.swing.JTextField txt_ciel;
    private javax.swing.JTextField txt_datDor;
    private javax.swing.JTextField txt_datVypr;
    private javax.swing.JTextField txt_idSnimaca;
    private javax.swing.JTextField txt_idVlaku_b;
    private javax.swing.JTextField txt_pridanieVozna_idSnimaca;
    private javax.swing.JTextField txt_pridanieVozna_idSpolocnosti;
    private javax.swing.JTextField txt_pridanieVozna_idVozna;
    private javax.swing.JTextField txt_pridanieVozna_kod;
    private javax.swing.JTextField txt_typ;
    private javax.swing.JTextField txt_typPohybu;
    private javax.swing.JTextField txt_vyradenieVoznaZVlaku_idSnimaca;
    private javax.swing.JTextField txt_vyradenieVoznaZVlaku_idVlaku;
    private javax.swing.JTextField txt_vyradenieVoznaZVlaku_idVozna;
    private javax.swing.JTextField txt_vyradenieVoznaZVlaku_kod;
    private javax.swing.JTextField txt_vytvorenieStanice_gpsDlzka;
    private javax.swing.JTextField txt_vytvorenieStanice_gpsSirka;
    private javax.swing.JTextField txt_vytvorenieStanice_nazov;
    private javax.swing.JTextField txt_zaciatok;
    private javax.swing.JTextField txt_zaradenieVoznaDoVlaku_idSnimaca;
    private javax.swing.JTextField txt_zaradenieVoznaDoVlaku_idVlaku;
    private javax.swing.JTextField txt_zaradenieVoznaDoVlaku_idVozna;
    private javax.swing.JTextField txt_zaradenieVoznaDoVlaku_kod;
    private javax.swing.JTextField txt_zmenaPolohyVozna_idSnimaca;
    private javax.swing.JTextField txt_zmenaPolohyVozna_idVozna;
    private javax.swing.JTextField txt_zmenaPolohyVozna_kod;
    private javax.swing.JTextField txt_zmenaPolohyVozna_poznamka;
    private javax.swing.JTextField txt_zobrazVozneVStanici_casDo;
    private javax.swing.JTextField txt_zobrazVozneVStanici_casOd;
    private javax.swing.JTextField txt_zobrazVozneVStanici_idStanice;
    // End of variables declaration//GEN-END:variables
}
