/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import core.DBmethods;

/**
 *
 * @author Silent1
 */
public class GUI extends javax.swing.JFrame {

    private DBmethods dbmethods;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        dbmethods = new DBmethods();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_vytvorVlak = new javax.swing.JDialog();
        txt_zaciatok = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ciel = new javax.swing.JTextField();
        txt_typ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_datVypr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_datDor = new javax.swing.JTextField();
        btn_createTrain = new javax.swing.JButton();
        btn_endTrainCreation = new javax.swing.JButton();
        dialog_vytvorPohybVoznaVlak = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_typPohybu = new javax.swing.JTextField();
        txt_idSnimaca = new javax.swing.JTextField();
        txt_idVlaku_b = new javax.swing.JTextField();
        btn_vytvorPohyb = new javax.swing.JButton();
        btn_koniec = new javax.swing.JButton();
        dialog_pridajVozen = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_pridanieVozna_idSpolocnosti = new javax.swing.JTextField();
        txt_pridanieVozna_kod = new javax.swing.JTextField();
        txt_pridanieVozna_idVozna = new javax.swing.JTextField();
        txt_pridanieVozna_idSnimaca = new javax.swing.JTextField();
        btn_pridanieVozna_pridaj = new javax.swing.JButton();
        btn_pridanieVozna_koniec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_createTrain = new javax.swing.JMenuItem();
        menu_vytvorPohybVoznaVlak = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btn_zobrazVlak = new javax.swing.JMenuItem();
        btn_zobrazPohybVoznaVlak = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_pridajVozen = new javax.swing.JMenuItem();
        menu_vyradVozen = new javax.swing.JMenuItem();
        menu_zaradVozenDoVlaku = new javax.swing.JMenuItem();
        menu_vyradVozenZVlaku = new javax.swing.JMenuItem();
        menu_zmenPolohuVozna = new javax.swing.JMenuItem();
        menu_vyhladajVozen = new javax.swing.JMenuItem();

        dialog_vytvorVlak.setMinimumSize(new java.awt.Dimension(400, 392));
        dialog_vytvorVlak.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        dialog_vytvorVlak.getContentPane().add(txt_zaciatok, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 90, -1));

        jLabel1.setText("Vytvaranie vlakov");
        dialog_vytvorVlak.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setText("Zaciatok:");
        dialog_vytvorVlak.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel3.setText("Ciel:");
        dialog_vytvorVlak.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 50, 20));
        dialog_vytvorVlak.getContentPane().add(txt_ciel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, -1));
        dialog_vytvorVlak.getContentPane().add(txt_typ, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 90, -1));

        jLabel4.setText("Typ:");
        dialog_vytvorVlak.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel5.setText("Datum vypravenia:");
        dialog_vytvorVlak.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));
        dialog_vytvorVlak.getContentPane().add(txt_datVypr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 90, -1));

        jLabel6.setText("Datum dorazenia:");
        dialog_vytvorVlak.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));
        dialog_vytvorVlak.getContentPane().add(txt_datDor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 90, -1));

        btn_createTrain.setText("Vytvor vlak");
        btn_createTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createTrainActionPerformed(evt);
            }
        });
        dialog_vytvorVlak.getContentPane().add(btn_createTrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        btn_endTrainCreation.setText("Koniec");
        btn_endTrainCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_endTrainCreationActionPerformed(evt);
            }
        });
        dialog_vytvorVlak.getContentPane().add(btn_endTrainCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        dialog_vytvorPohybVoznaVlak.setMinimumSize(new java.awt.Dimension(400, 402));
        dialog_vytvorPohybVoznaVlak.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Vytvorenie pohybu vozna");
        dialog_vytvorPohybVoznaVlak.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel8.setText("Typ pohybu:");
        dialog_vytvorPohybVoznaVlak.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 20));

        jLabel9.setText("Id_snimaca:");
        dialog_vytvorPohybVoznaVlak.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel10.setText("Id_vlaku:");
        dialog_vytvorPohybVoznaVlak.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));
        dialog_vytvorPohybVoznaVlak.getContentPane().add(txt_typPohybu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, -1));
        dialog_vytvorPohybVoznaVlak.getContentPane().add(txt_idSnimaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 70, -1));
        dialog_vytvorPohybVoznaVlak.getContentPane().add(txt_idVlaku_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 70, -1));

        btn_vytvorPohyb.setText("Vytvor pohyb");
        btn_vytvorPohyb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vytvorPohybActionPerformed(evt);
            }
        });
        dialog_vytvorPohybVoznaVlak.getContentPane().add(btn_vytvorPohyb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        btn_koniec.setText("Koniec");
        btn_koniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_koniecActionPerformed(evt);
            }
        });
        dialog_vytvorPohybVoznaVlak.getContentPane().add(btn_koniec, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        dialog_pridajVozen.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel11.setText("Pridanie vozna");

        jLabel12.setText("ID spolocnosti:");

        jLabel13.setText("Kod:");

        jLabel14.setText("ID vozna:");

        jLabel15.setText("ID snimaca:");

        txt_pridanieVozna_kod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pridanieVozna_kodActionPerformed(evt);
            }
        });

        btn_pridanieVozna_pridaj.setText("Pridaj vozen");
        btn_pridanieVozna_pridaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pridanieVozna_pridajActionPerformed(evt);
            }
        });

        btn_pridanieVozna_koniec.setText("Koniec");
        btn_pridanieVozna_koniec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pridanieVozna_koniecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_pridajVozenLayout = new javax.swing.GroupLayout(dialog_pridajVozen.getContentPane());
        dialog_pridajVozen.getContentPane().setLayout(dialog_pridajVozenLayout);
        dialog_pridajVozenLayout.setHorizontalGroup(
            dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel11))
                    .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(36, 36, 36)
                        .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pridanieVozna_idSnimaca, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(txt_pridanieVozna_idVozna)
                            .addComponent(txt_pridanieVozna_kod)
                            .addComponent(txt_pridanieVozna_idSpolocnosti))))
                .addGap(133, 133, 133))
            .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btn_pridanieVozna_pridaj))
                    .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btn_pridanieVozna_koniec)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialog_pridajVozenLayout.setVerticalGroup(
            dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_pridajVozenLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(45, 45, 45)
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_pridanieVozna_idSpolocnosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_pridanieVozna_kod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_pridanieVozna_idVozna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_pridajVozenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txt_pridanieVozna_idSnimaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_pridanieVozna_pridaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_pridanieVozna_koniec)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jMenu1.setText("File");

        menu_Exit.setText("Exit");
        menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vytvor");

        menu_createTrain.setText("Vytvor vlak");
        menu_createTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_createTrainActionPerformed(evt);
            }
        });
        jMenu2.add(menu_createTrain);

        menu_vytvorPohybVoznaVlak.setText("Vytvor pohyb vozna - vlak");
        menu_vytvorPohybVoznaVlak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vytvorPohybVoznaVlakActionPerformed(evt);
            }
        });
        jMenu2.add(menu_vytvorPohybVoznaVlak);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Zobraz tabulku");

        btn_zobrazVlak.setText("Vlak");
        btn_zobrazVlak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zobrazVlakActionPerformed(evt);
            }
        });
        jMenu3.add(btn_zobrazVlak);

        btn_zobrazPohybVoznaVlak.setText("Pohyb vozna vlak");
        btn_zobrazPohybVoznaVlak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zobrazPohybVoznaVlakActionPerformed(evt);
            }
        });
        jMenu3.add(btn_zobrazPohybVoznaVlak);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("PL/SQL ulohy");

        menu_pridajVozen.setText("Pridaj vozen");
        menu_pridajVozen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pridajVozenActionPerformed(evt);
            }
        });
        jMenu4.add(menu_pridajVozen);

        menu_vyradVozen.setText("Vyrad vozen");
        menu_vyradVozen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vyradVozenActionPerformed(evt);
            }
        });
        jMenu4.add(menu_vyradVozen);

        menu_zaradVozenDoVlaku.setText("Zarad vozen do vlaku");
        menu_zaradVozenDoVlaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zaradVozenDoVlakuActionPerformed(evt);
            }
        });
        jMenu4.add(menu_zaradVozenDoVlaku);

        menu_vyradVozenZVlaku.setText("Vyrad vozen z vlaku");
        menu_vyradVozenZVlaku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vyradVozenZVlakuActionPerformed(evt);
            }
        });
        jMenu4.add(menu_vyradVozenZVlaku);

        menu_zmenPolohuVozna.setText("Zmen polohu vozna v stanici");
        menu_zmenPolohuVozna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_zmenPolohuVoznaActionPerformed(evt);
            }
        });
        jMenu4.add(menu_zmenPolohuVozna);

        menu_vyhladajVozen.setText("Vyhladaj najblizsi volny vozen");
        menu_vyhladajVozen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_vyhladajVozenActionPerformed(evt);
            }
        });
        jMenu4.add(menu_vyhladajVozen);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_ExitActionPerformed

    private void btn_createTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createTrainActionPerformed
        
        int    zaciatok  = Integer.parseInt(txt_zaciatok.getText());
        int    ciel      = Integer.parseInt(txt_ciel.getText());
        int    typ       = Integer.parseInt(txt_typ.getText());
        String datVyp    = txt_datVypr.getText();
        String datDor    = txt_datDor.getText();
        
        dbmethods.vytvorVlak(zaciatok, ciel, typ, datVyp, datDor);
        
    }//GEN-LAST:event_btn_createTrainActionPerformed

    private void menu_createTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_createTrainActionPerformed
        dialog_vytvorVlak.pack();
        dialog_vytvorVlak.setVisible(true);
    }//GEN-LAST:event_menu_createTrainActionPerformed

    private void btn_endTrainCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_endTrainCreationActionPerformed
        dialog_vytvorVlak.setVisible(false);
    }//GEN-LAST:event_btn_endTrainCreationActionPerformed

    private void btn_vytvorPohybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vytvorPohybActionPerformed
        
        char   typPohybu = txt_typPohybu.getText().charAt(0);
        int    idSnimaca = Integer.parseInt(txt_idSnimaca.getText());
        int    idVlaku   = Integer.parseInt(txt_idVlaku_b.getText());
        
        dbmethods.vytvorPohybVoznaVlak(typPohybu, idSnimaca, idVlaku);
        
    }//GEN-LAST:event_btn_vytvorPohybActionPerformed

    private void btn_koniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_koniecActionPerformed
        dialog_vytvorPohybVoznaVlak.setVisible(false);
    }//GEN-LAST:event_btn_koniecActionPerformed

    private void menu_vytvorPohybVoznaVlakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vytvorPohybVoznaVlakActionPerformed
        dialog_vytvorPohybVoznaVlak.pack();
        dialog_vytvorPohybVoznaVlak.setVisible(true);
    }//GEN-LAST:event_menu_vytvorPohybVoznaVlakActionPerformed

    private void btn_zobrazVlakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zobrazVlakActionPerformed
        txtArea.setText(dbmethods.zobrazVlak());
    }//GEN-LAST:event_btn_zobrazVlakActionPerformed

    private void btn_zobrazPohybVoznaVlakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zobrazPohybVoznaVlakActionPerformed
        txtArea.setText(dbmethods.zobrazPohybVoznaVlak());
    }//GEN-LAST:event_btn_zobrazPohybVoznaVlakActionPerformed

    private void menu_pridajVozenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pridajVozenActionPerformed
        dialog_pridajVozen.pack();
        dialog_pridajVozen.setVisible(true);
    }//GEN-LAST:event_menu_pridajVozenActionPerformed

    private void menu_vyradVozenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vyradVozenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_vyradVozenActionPerformed

    private void menu_zaradVozenDoVlakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zaradVozenDoVlakuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_zaradVozenDoVlakuActionPerformed

    private void menu_vyradVozenZVlakuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vyradVozenZVlakuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_vyradVozenZVlakuActionPerformed

    private void menu_zmenPolohuVoznaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_zmenPolohuVoznaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_zmenPolohuVoznaActionPerformed

    private void menu_vyhladajVozenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_vyhladajVozenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_vyhladajVozenActionPerformed

    private void txt_pridanieVozna_kodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pridanieVozna_kodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pridanieVozna_kodActionPerformed

    private void btn_pridanieVozna_pridajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pridanieVozna_pridajActionPerformed
        int idSpolocnosti = Integer.parseInt(txt_pridanieVozna_idSpolocnosti.getText());
        int kod           = Integer.parseInt(txt_pridanieVozna_kod.getText());
        int idVozna       = Integer.parseInt(txt_pridanieVozna_idVozna.getText());
        int idSnimaca     = Integer.parseInt(txt_pridanieVozna_idSnimaca.getText());
        
        dbmethods.pridajVozen(idSpolocnosti, kod, idVozna, idSnimaca);
    }//GEN-LAST:event_btn_pridanieVozna_pridajActionPerformed

    private void btn_pridanieVozna_koniecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pridanieVozna_koniecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pridanieVozna_koniecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createTrain;
    private javax.swing.JButton btn_endTrainCreation;
    private javax.swing.JButton btn_koniec;
    private javax.swing.JButton btn_pridanieVozna_koniec;
    private javax.swing.JButton btn_pridanieVozna_pridaj;
    private javax.swing.JButton btn_vytvorPohyb;
    private javax.swing.JMenuItem btn_zobrazPohybVoznaVlak;
    private javax.swing.JMenuItem btn_zobrazVlak;
    private javax.swing.JDialog dialog_pridajVozen;
    private javax.swing.JDialog dialog_vytvorPohybVoznaVlak;
    private javax.swing.JDialog dialog_vytvorVlak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu_Exit;
    private javax.swing.JMenuItem menu_createTrain;
    private javax.swing.JMenuItem menu_pridajVozen;
    private javax.swing.JMenuItem menu_vyhladajVozen;
    private javax.swing.JMenuItem menu_vyradVozen;
    private javax.swing.JMenuItem menu_vyradVozenZVlaku;
    private javax.swing.JMenuItem menu_vytvorPohybVoznaVlak;
    private javax.swing.JMenuItem menu_zaradVozenDoVlaku;
    private javax.swing.JMenuItem menu_zmenPolohuVozna;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txt_ciel;
    private javax.swing.JTextField txt_datDor;
    private javax.swing.JTextField txt_datVypr;
    private javax.swing.JTextField txt_idSnimaca;
    private javax.swing.JTextField txt_idVlaku_b;
    private javax.swing.JTextField txt_pridanieVozna_idSnimaca;
    private javax.swing.JTextField txt_pridanieVozna_idSpolocnosti;
    private javax.swing.JTextField txt_pridanieVozna_idVozna;
    private javax.swing.JTextField txt_pridanieVozna_kod;
    private javax.swing.JTextField txt_typ;
    private javax.swing.JTextField txt_typPohybu;
    private javax.swing.JTextField txt_zaciatok;
    // End of variables declaration//GEN-END:variables
}
